config = require("../server/config");
const server = config.production
  ? "https://titan-esports.org:7001"
  : "http://localhost:7001";

let index = 0;

module.exports = {
  aatrox: {
    suspended: false,
    name: "Aatrox",
    loadingImg: `img/champion/loading/Aatrox_0.jpg`,
    splashImg: `img/champion/splash/Aatrox_0.jpg`,
    tileImg: `img/champion/tiles/Aatrox_0.jpg`,
    vid: `champion_videos/c-o-animated-aatrox.mp4`,
    pickAudio: `audio/champion_audio/aatrox/pick/0.ogg`,
    banAudio: `audio/champion_audio/aatrox/ban/0.ogg`,
  },
  ahri: {
    suspended: false,
    name: "Ahri",
    loadingImg: `img/champion/loading/Ahri_0.jpg`,
    splashImg: `img/champion/splash/Ahri_0.jpg`,
    tileImg: `img/champion/tiles/Ahri_0.jpg`,
    vid: `champion_videos/c-o-animated-ahri.mp4`,
    pickAudio: `audio/champion_audio/ahri/pick/0.ogg`,
    banAudio: `audio/champion_audio/ahri/ban/0.ogg`,
  },
  akali: {
    suspended: false,
    name: "Akali",
    loadingImg: `img/champion/loading/Akali_0.jpg`,
    splashImg: `img/champion/splash/Akali_0.jpg`,
    tileImg: `img/champion/tiles/Akali_0.jpg`,
    vid: `champion_videos/c-o-animated-akali.mp4`,
    pickAudio: `audio/champion_audio/akali/pick/0.ogg`,
    banAudio: `audio/champion_audio/akali/ban/0.ogg`,
  },
  alistar: {
    suspended: false,
    name: "Alistar",
    loadingImg: `img/champion/loading/Alistar_0.jpg`,
    splashImg: `img/champion/splash/Alistar_0.jpg`,
    tileImg: `img/champion/tiles/Alistar_0.jpg`,
    vid: `champion_videos/c-o-animated-alistar.mp4`,
    pickAudio: `audio/champion_audio/alistar/pick/0.ogg`,
    banAudio: `audio/champion_audio/alistar/ban/0.ogg`,
  },
  amumu: {
    suspended: false,
    name: "Amumu",
    loadingImg: `img/champion/loading/Amumu_0.jpg`,
    splashImg: `img/champion/splash/Amumu_0.jpg`,
    tileImg: `img/champion/tiles/Amumu_0.jpg`,
    vid: `champion_videos/c-o-animated-amumu.mp4`,
    pickAudio: `audio/champion_audio/amumu/pick/0.ogg`,
    banAudio: `audio/champion_audio/amumu/ban/0.ogg`,
  },
  anivia: {
    suspended: false,
    name: "Anivia",
    loadingImg: `img/champion/loading/Anivia_0.jpg`,
    splashImg: `img/champion/splash/Anivia_0.jpg`,
    tileImg: `img/champion/tiles/Anivia_0.jpg`,
    vid: `champion_videos/c-o-animated-anivia.mp4`,
    pickAudio: `audio/champion_audio/anivia/pick/0.ogg`,
    banAudio: `audio/champion_audio/anivia/ban/0.ogg`,
  },
  annie: {
    suspended: false,
    name: "Annie",
    loadingImg: `img/champion/loading/Annie_0.jpg`,
    splashImg: `img/champion/splash/Annie_0.jpg`,
    tileImg: `img/champion/tiles/Annie_0.jpg`,
    vid: `champion_videos/c-o-animated-annie.mp4`,
    pickAudio: `audio/champion_audio/annie/pick/0.ogg`,
    banAudio: `audio/champion_audio/annie/ban/0.ogg`,
  },
  aphelios: {
    suspended: false,
    name: "Aphelios",
    loadingImg: `img/champion/loading/Aphelios_0.jpg`,
    splashImg: `img/champion/splash/Aphelios_0.jpg`,
    tileImg: `img/champion/tiles/Aphelios_0.jpg`,
    vid: `champion_videos/c-o-animated-senna.mp4`,
    pickAudio: `audio/champion_audio/aphelios/pick/0.mp3`,
    banAudio: `audio/champion_audio/aphelios/ban/0.mp3`,
  },
  ashe: {
    suspended: false,
    name: "Ashe",
    loadingImg: `img/champion/loading/Ashe_0.jpg`,
    splashImg: `img/champion/splash/Ashe_0.jpg`,
    tileImg: `img/champion/tiles/Ashe_0.jpg`,
    vid: `champion_videos/c-o-animated-ashe.mp4`,
    pickAudio: `audio/champion_audio/ashe/pick/0.ogg`,
    banAudio: `audio/champion_audio/ashe/ban/0.ogg`,
  },
  aurelion_sol: {
    suspended: false,
    name: "Aurelion Sol",
    loadingImg: `img/champion/loading/AurelionSol_0.jpg`,
    splashImg: `img/champion/splash/AurelionSol_0.jpg`,
    tileImg: `img/champion/tiles/AurelionSol_0.jpg`,
    vid: `champion_videos/c-o-animated-aurelionsol.mp4`,
    pickAudio: `audio/champion_audio/aurelionsol/pick/0.ogg`,
    banAudio: `audio/champion_audio/aurelionsol/ban/0.ogg`,
  },
  azir: {
    suspended: false,
    name: "Azir",
    loadingImg: `img/champion/loading/Azir_0.jpg`,
    splashImg: `img/champion/splash/Azir_0.jpg`,
    tileImg: `img/champion/tiles/Azir_0.jpg`,
    vid: `champion_videos/c-o-animated-azir.mp4`,
    pickAudio: `audio/champion_audio/azir/pick/0.ogg`,
    banAudio: `audio/champion_audio/azir/ban/0.ogg`,
  },
  bard: {
    suspended: false,
    name: "Bard",
    loadingImg: `img/champion/loading/Bard_0.jpg`,
    splashImg: `img/champion/splash/Bard_0.jpg`,
    tileImg: `img/champion/tiles/Bard_0.jpg`,
    vid: `champion_videos/c-o-animated-bard.mp4`,
    pickAudio: `audio/champion_audio/bard/pick/0.ogg`,
    banAudio: `audio/champion_audio/bard/ban/0.ogg`,
  },
  blitzcrank: {
    suspended: false,
    name: "Blitzcrank",
    loadingImg: `img/champion/loading/Blitzcrank_0.jpg`,
    splashImg: `img/champion/splash/Blitzcrank_0.jpg`,
    tileImg: `img/champion/tiles/Blitzcrank_0.jpg`,
    vid: `champion_videos/c-o-animated/blitzcrank.mp4`,
    pickAudio: `audio/champion_audio/blitzcrank/pick/0.ogg`,
    banAudio: `audio/champion_audio/blitzcrank/ban/0.ogg`,
  },
  brand: {
    suspended: false,
    name: "Brand",
    loadingImg: `img/champion/loading/Brand_0.jpg`,
    splashImg: `img/champion/splash/Brand_0.jpg`,
    tileImg: `img/champion/tiles/Brand_0.jpg`,
    vid: `champion_videos/c-o-animated-brand.mp4`,
    pickAudio: `audio/champion_audio/brand/pick/0.ogg`,
    banAudio: `audio/champion_audio/brand/ban/0.ogg`,
  },
  braum: {
    suspended: false,
    name: "Braum",
    loadingImg: `img/champion/loading/Braum_0.jpg`,
    splashImg: `img/champion/splash/Braum_0.jpg`,
    tileImg: `img/champion/tiles/Braum_0.jpg`,
    vid: `champion_videos/c-o-animated-braum.mp4`,
    pickAudio: `audio/champion_audio/braum/pick/0.ogg`,
    banAudio: `audio/champion_audio/braum/ban/0.ogg`,
  },
  caitlyn: {
    suspended: false,
    name: "Caitlyn",
    loadingImg: `img/champion/loading/Caitlyn_0.jpg`,
    splashImg: `img/champion/splash/Caitlyn_0.jpg`,
    tileImg: `img/champion/tiles/Caitlyn_0.jpg`,
    vid: `champion_videos/c-o-animated-caitlyn.mp4`,
    pickAudio: `audio/champion_audio/caitlyn/pick/0.ogg`,
    banAudio: `audio/champion_audio/caitlyn/ban/0.ogg`,
  },
  camille: {
    suspended: false,
    name: "Camille",
    loadingImg: `img/champion/loading/Camille_0.jpg`,
    splashImg: `img/champion/splash/Camille_0.jpg`,
    tileImg: `img/champion/tiles/Camille_0.jpg`,
    vid: `champion_videos/c-o-animated-camille.mp4`,
    pickAudio: `audio/champion_audio/camille/pick/0.ogg`,
    banAudio: `audio/champion_audio/camille/ban/0.ogg`,
  },
  cassiopeia: {
    suspended: false,
    name: "Cassiopeia",
    loadingImg: `img/champion/loading/Cassiopeia_0.jpg`,
    splashImg: `img/champion/splash/Cassiopeia_0.jpg`,
    tileImg: `img/champion/tiles/Cassiopeia_0.jpg`,
    vid: `champion_videos/c-o-animated-cassiopeia.mp4`,
    pickAudio: `audio/champion_audio/cassiopeia/pick/0.ogg`,
    banAudio: `audio/champion_audio/cassiopeia/ban/0.ogg`,
  },
  chogath: {
    suspended: false,
    name: "Chogath",
    loadingImg: `img/champion/loading/Chogath_0.jpg`,
    splashImg: `img/champion/splash/Chogath_0.jpg`,
    tileImg: `img/champion/tiles/Chogath_0.jpg`,
    vid: `champion_videos/c-o-animated-chogath.mp4`,
    pickAudio: `audio/champion_audio/chogath/pick/0.ogg`,
    banAudio: `audio/champion_audio/chogath/ban/0.ogg`,
  },
  corki: {
    suspended: false,
    name: "Corki",
    loadingImg: `img/champion/loading/Corki_0.jpg`,
    splashImg: `img/champion/splash/Corki_0.jpg`,
    tileImg: `img/champion/tiles/Corki_0.jpg`,
    vid: `champion_videos/c-o-animated-corki.mp4`,
    pickAudio: `audio/champion_audio/corki/pick/0.ogg`,
    banAudio: `audio/champion_audio/corki/ban/0.ogg`,
  },
  darius: {
    suspended: false,
    name: "Darius",
    loadingImg: `img/champion/loading/Darius_0.jpg`,
    splashImg: `img/champion/splash/Darius_0.jpg`,
    tileImg: `img/champion/tiles/Darius_0.jpg`,
    vid: `champion_videos/c-o-animated-darius.mp4`,
    pickAudio: `audio/champion_audio/darius/pick/0.ogg`,
    banAudio: `audio/champion_audio/darius/ban/0.ogg`,
  },
  diana: {
    suspended: false,
    name: "Diana",
    loadingImg: `img/champion/loading/Diana_0.jpg`,
    splashImg: `img/champion/splash/Diana_0.jpg`,
    tileImg: `img/champion/tiles/Diana_0.jpg`,
    vid: `champion_videos/c-o-animated-diana.mp4`,
    pickAudio: `audio/champion_audio/diana/pick/0.ogg`,
    banAudio: `audio/champion_audio/diana/ban/0.ogg`,
  },
  drmundo: {
    suspended: false,
    name: "Dr. Mundo",
    loadingImg: `img/champion/loading/DrMundo_0.jpg`,
    splashImg: `img/champion/splash/DrMundo_0.jpg`,
    tileImg: `img/champion/tiles/DrMundo_0.jpg`,
    vid: `champion_videos/c-o-animated-drmundo.mp4`,
    pickAudio: `audio/champion_audio/drmundo/pick/0.ogg`,
    banAudio: `audio/champion_audio/drmundo/ban/0.ogg`,
  },
  draven: {
    suspended: false,
    name: "Draven",
    loadingImg: `img/champion/loading/Draven_0.jpg`,
    splashImg: `img/champion/splash/Draven_0.jpg`,
    tileImg: `img/champion/tiles/Draven_0.jpg`,
    vid: `champion_videos/c-o-animated-draven.mp4`,
    pickAudio: `audio/champion_audio/draven/pick/0.ogg`,
    banAudio: `audio/champion_audio/draven/ban/0.ogg`,
  },
  ekko: {
    suspended: false,
    name: "Ekko",
    loadingImg: `img/champion/loading/Ekko_0.jpg`,
    splashImg: `img/champion/splash/Ekko_0.jpg`,
    tileImg: `img/champion/tiles/Ekko_0.jpg`,
    vid: `champion_videos/c-o-animated-ekko.mp4`,
    pickAudio: `audio/champion_audio/ekko/pick/0.ogg`,
    banAudio: `audio/champion_audio/ekko/ban/0.ogg`,
  },
  elise: {
    suspended: false,
    name: "Elise",
    loadingImg: `img/champion/loading/Elise_0.jpg`,
    splashImg: `img/champion/splash/Elise_0.jpg`,
    tileImg: `img/champion/tiles/Elise_0.jpg`,
    vid: `champion_videos/c-o-animated-elise.mp4`,
    pickAudio: `audio/champion_audio/elise/pick/0.ogg`,
    banAudio: `audio/champion_audio/elise/ban/0.ogg`,
  },
  evelynn: {
    suspended: false,
    name: "Evelynn",
    loadingImg: `img/champion/loading/Evelynn_0.jpg`,
    splashImg: `img/champion/splash/Evelynn_0.jpg`,
    tileImg: `img/champion/tiles/Evelynn_0.jpg`,
    vid: `champion_videos/c-o-animated-evelynn.mp4`,
    pickAudio: `audio/champion_audio/evelynn/pick/0.ogg`,
    banAudio: `audio/champion_audio/evelynn/ban/0.ogg`,
  },
  ezreal: {
    suspended: false,
    name: "Ezreal",
    loadingImg: `img/champion/loading/Ezreal_0.jpg`,
    splashImg: `img/champion/splash/Ezreal_0.jpg`,
    tileImg: `img/champion/tiles/Ezreal_0.jpg`,
    vid: `champion_videos/c-o-animated-ezreal.mp4`,
    pickAudio: `audio/champion_audio/ezreal/pick/0.ogg`,
    banAudio: `audio/champion_audio/ezreal/ban/0.ogg`,
  },
  fiddlesticks: {
    suspended: false,
    name: "Fiddlesticks",
    loadingImg: `img/champion/loading/FiddleSticks_0.jpg`,
    splashImg: `img/champion/splash/FiddleSticks_0.jpg`,
    tileImg: `img/champion/tiles/FiddleSticks_0.jpg`,
    vid: `champion_videos/c-o-animated-fiddlesticks.mp4`,
    pickAudio: `audio/champion_audio/fiddlesticks/pick/0.ogg`,
    banAudio: `audio/champion_audio/fiddlesticks/ban/0.ogg`,
  },
  fiora: {
    suspended: false,
    name: "Fiora",
    loadingImg: `img/champion/loading/Fiora_0.jpg`,
    splashImg: `img/champion/splash/Fiora_0.jpg`,
    tileImg: `img/champion/tiles/Fiora_0.jpg`,
    vid: `champion_videos/c-o-animated-fiora.mp4`,
    pickAudio: `audio/champion_audio/fiora/pick/0.ogg`,
    banAudio: `audio/champion_audio/fiora/ban/0.ogg`,
  },
  fizz: {
    suspended: false,
    name: "Fizz",
    loadingImg: `img/champion/loading/Fizz_0.jpg`,
    splashImg: `img/champion/splash/Fizz_0.jpg`,
    tileImg: `img/champion/tiles/Fizz_0.jpg`,
    vid: `champion_videos/c-o-animated-fizz.mp4`,
    pickAudio: `audio/champion_audio/fizz/pick/0.ogg`,
    banAudio: `audio/champion_audio/fizz/ban/0.ogg`,
  },
  galio: {
    suspended: false,
    name: "Galio",
    loadingImg: `img/champion/loading/Galio_0.jpg`,
    splashImg: `img/champion/splash/Galio_0.jpg`,
    tileImg: `img/champion/tiles/Galio_0.jpg`,
    vid: `champion_videos/c-o-animated-galio.mp4`,
    pickAudio: `audio/champion_audio/galio/pick/0.ogg`,
    banAudio: `audio/champion_audio/gangplank/ban/0.ogg`,
  },
  gangplank: {
    suspended: false,
    name: "Gangplank",
    loadingImg: `img/champion/loading/Gangplank_0.jpg`,
    splashImg: `img/champion/splash/Gangplank_0.jpg`,
    tileImg: `img/champion/tiles/Gangplank_0.jpg`,
    vid: `champion_videos/c-o-animated-gangplank.mp4`,
    pickAudio: `audio/champion_audio/gangplank/pick/0.ogg`,
    banAudio: `audio/champion_audio/gangplank/ban/0.ogg`,
  },
  garen: {
    suspended: false,
    name: "Garen",
    loadingImg: `img/champion/loading/Garen_0.jpg`,
    splashImg: `img/champion/splash/Garen_0.jpg`,
    tileImg: `img/champion/tiles/Garen_0.jpg`,
    vid: `champion_videos/c-o-animated-garen.mp4`,
    pickAudio: `audio/champion_audio/garen/pick/0.ogg`,
    banAudio: `audio/champion_audio/garen/ban/0.ogg`,
  },
  gnar: {
    suspended: false,
    name: "Gnar",
    loadingImg: `img/champion/loading/Gnar_0.jpg`,
    splashImg: `img/champion/splash/Gnar_0.jpg`,
    tileImg: `img/champion/tiles/Gnar_0.jpg`,
    vid: `champion_videos/c-o-animated-gnar.mp4`,
    pickAudio: `audio/champion_audio/gnar/pick/0.ogg`,
    banAudio: `audio/champion_audio/gnar/ban/0.ogg`,
  },
  gragas: {
    suspended: false,
    name: "Gragas",
    loadingImg: `img/champion/loading/Gragas_0.jpg`,
    splashImg: `img/champion/splash/Gragas_0.jpg`,
    tileImg: `img/champion/tiles/Gragas_0.jpg`,
    vid: `champion_videos/c-o-animated-gragas.mp4`,
    pickAudio: `audio/champion_audio/gragas/pick/0.ogg`,
    banAudio: `audio/champion_audio/gragas/ban/0.ogg`,
  },
  graves: {
    suspended: false,
    name: "Graves",
    loadingImg: `img/champion/loading/Graves_0.jpg`,
    splashImg: `img/champion/splash/Graves_0.jpg`,
    tileImg: `img/champion/tiles/Graves_0.jpg`,
    vid: `champion_videos/c-o-animated-graves.mp4`,
    pickAudio: `audio/champion_audio/graves/pick/0.ogg`,
    banAudio: `audio/champion_audio/graves/ban/0.ogg`,
  },
  hecarim: {
    suspended: false,
    name: "Hecarim",
    loadingImg: `img/champion/loading/Hecarim_0.jpg`,
    splashImg: `img/champion/splash/Hecarim_0.jpg`,
    tileImg: `img/champion/tiles/Hecarim_0.jpg`,
    vid: `champion_videos/c-o-animated-hecarim.mp4`,
    pickAudio: `audio/champion_audio/hecarim/pick/0.ogg`,
    banAudio: `audio/champion_audio/hecarim/ban/0.ogg`,
  },
  heimerdinger: {
    suspended: false,
    name: "Heimerdinger",
    loadingImg: `img/champion/loading/Heimerdinger_0.jpg`,
    splashImg: `img/champion/splash/Heimerdinger_0.jpg`,
    tileImg: `img/champion/tiles/Heimerdinger_0.jpg`,
    vid: `champion_videos/c-o-animated-heimerdinger.mp4`,
    pickAudio: `audio/champion_audio/heimerdinger/pick/0.ogg`,
    banAudio: `audio/champion_audio/heimerdinger/ban/0.ogg`,
  },
  illaoi: {
    suspended: false,
    name: "Illaoi",
    loadingImg: `img/champion/loading/Illaoi_0.jpg`,
    splashImg: `img/champion/splash/Illaoi_0.jpg`,
    tileImg: `img/champion/tiles/Illaoi_0.jpg`,
    vid: `champion_videos/c-o-animated-illaoi.mp4`,
    pickAudio: `audio/champion_audio/illaoi/pick/0.ogg`,
    banAudio: `audio/champion_audio/illaoi/ban/0.ogg`,
  },
  irelia: {
    suspended: false,
    name: "Irelia",
    loadingImg: `img/champion/loading/Irelia_0.jpg`,
    splashImg: `img/champion/splash/Irelia_0.jpg`,
    tileImg: `img/champion/tiles/Irelia_0.jpg`,
    vid: `champion_videos/c-o-animated-irelia.mp4`,
    pickAudio: `audio/champion_audio/irelia/pick/0.ogg`,
    banAudio: `audio/champion_audio/irelia/ban/0.ogg`,
  },
  ivern: {
    suspended: false,
    name: "Ivern",
    loadingImg: `img/champion/loading/Ivern_0.jpg`,
    splashImg: `img/champion/splash/Ivern_0.jpg`,
    tileImg: `img/champion/tiles/Ivern_0.jpg`,
    vid: `champion_videos/c-o-animated-ivern.mp4`,
    pickAudio: `audio/champion_audio/ivern/pick/0.ogg`,
    banAudio: `audio/champion_audio/ivern/ban/0.ogg`,
  },
  janna: {
    suspended: false,
    name: "Janna",
    loadingImg: `img/champion/loading/Janna_0.jpg`,
    splashImg: `img/champion/splash/Janna_0.jpg`,
    tileImg: `img/champion/tiles/Janna_0.jpg`,
    vid: `champion_videos/c-o-animated-janna.mp4`,
    pickAudio: `audio/champion_audio/janna/pick/0.ogg`,
    banAudio: `audio/champion_audio/janna/ban/0.ogg`,
  },
  jarvanIV: {
    suspended: false,
    name: "JarvanIV",
    loadingImg: `img/champion/loading/JarvanIV_0.jpg`,
    splashImg: `img/champion/splash/JarvanIV_0.jpg`,
    tileImg: `img/champion/tiles/JarvanIV_0.jpg`,
    vid: `champion_videos/c-o-animated-jarvanIV.mp4`,
    pickAudio: `audio/champion_audio/jarvanIV/pick/0.ogg`,
    banAudio: `audio/champion_audio/jarvanIV/ban/0.ogg`,
  },
  jax: {
    suspended: false,
    name: "Jax",
    loadingImg: `img/champion/loading/Jax_0.jpg`,
    splashImg: `img/champion/splash/Jax_0.jpg`,
    tileImg: `img/champion/tiles/Jax_0.jpg`,
    vid: `champion_videos/c-o-animated-jax.mp4`,
    pickAudio: `audio/champion_audio/jax/pick/0.ogg`,
    banAudio: `audio/champion_audio/jax/ban/0.ogg`,
  },
  jayce: {
    suspended: false,
    name: "Jayce",
    loadingImg: `img/champion/loading/Jayce_0.jpg`,
    splashImg: `img/champion/splash/Jayce_0.jpg`,
    tileImg: `img/champion/tiles/Jayce_0.jpg`,
    vid: `champion_videos/c-o-animated-jayce.mp4`,
    pickAudio: `audio/champion_audio/jayce/pick/0.ogg`,
    banAudio: `audio/champion_audio/jayce/ban/0.ogg`,
  },
  jhin: {
    suspended: false,
    name: "Jhin",
    loadingImg: `img/champion/loading/Jhin_0.jpg`,
    splashImg: `img/champion/splash/Jhin_0.jpg`,
    tileImg: `img/champion/tiles/Jhin_0.jpg`,
    vid: `champion_videos/c-o-animated-jhin.mp4`,
    pickAudio: `audio/champion_audio/jhin/pick/0.ogg`,
    banAudio: `audio/champion_audio/jhin/ban/0.ogg`,
  },
  jinx: {
    suspended: false,
    name: "Jinx",
    loadingImg: `img/champion/loading/Jinx_0.jpg`,
    splashImg: `img/champion/splash/Jinx_0.jpg`,
    tileImg: `img/champion/tiles/Jinx_0.jpg`,
    vid: `champion_videos/c-o-animated-jinx.mp4`,
    pickAudio: `audio/champion_audio/jinx/pick/0.ogg`,
    banAudio: `audio/champion_audio/jinx/ban/0.ogg`,
  },
  kaisa: {
    suspended: false,
    name: "Kai'Sa",
    loadingImg: `img/champion/loading/Kaisa_0.jpg`,
    splashImg: `img/champion/splash/Kaisa_0.jpg`,
    tileImg: `img/champion/tiles/Kaisa_0.jpg`,
    vid: `champion_videos/c-o-animated-kaisa.mp4`,
    pickAudio: `audio/champion_audio/kaisa/pick/0.ogg`,
    banAudio: `audio/champion_audio/kaisa/ban/0.ogg`,
  },
  kalista: {
    suspended: false,
    name: "Kalista",
    loadingImg: `img/champion/loading/Kalista_0.jpg`,
    splashImg: `img/champion/splash/Kalista_0.jpg`,
    tileImg: `img/champion/tiles/Kalista_0.jpg`,
    vid: `champion_videos/c-o-animated-kalista.mp4`,
    pickAudio: `audio/champion_audio/kalista/pick/0.ogg`,
    banAudio: `audio/champion_audio/kalista/ban/0.ogg`,
  },
  karma: {
    suspended: false,
    name: "Karma",
    loadingImg: `img/champion/loading/Karma_0.jpg`,
    splashImg: `img/champion/splash/Karma_0.jpg`,
    tileImg: `img/champion/tiles/Karma_0.jpg`,
    vid: `champion_videos/c-o-animated-karma.mp4`,
    pickAudio: `audio/champion_audio/karma/pick/0.ogg`,
    banAudio: `audio/champion_audio/karma/ban/0.ogg`,
  },
  karthus: {
    suspended: false,
    name: "Karthus",
    loadingImg: `img/champion/loading/Karthus_0.jpg`,
    splashImg: `img/champion/splash/Karthus_0.jpg`,
    tileImg: `img/champion/tiles/Karthus_0.jpg`,
    vid: `champion_videos/c-o-animated-karthus.mp4`,
    pickAudio: `audio/champion_audio/karthus/pick/0.ogg`,
    banAudio: `audio/champion_audio/karthus/ban/0.ogg`,
  },
  kassadin: {
    suspended: false,
    name: "Kassadin",
    loadingImg: `img/champion/loading/Kassadin_0.jpg`,
    splashImg: `img/champion/splash/Kassadin_0.jpg`,
    tileImg: `img/champion/tiles/Kassadin_0.jpg`,
    vid: `champion_videos/c-o-animated-kassadin.mp4`,
    pickAudio: `audio/champion_audio/kassadin/pick/0.ogg`,
    banAudio: `audio/champion_audio/kassadin/ban/0.ogg`,
  },
  katarina: {
    suspended: false,
    name: "Katarina",
    loadingImg: `img/champion/loading/Katarina_0.jpg`,
    splashImg: `img/champion/splash/Katarina_0.jpg`,
    tileImg: `img/champion/tiles/Katarina_0.jpg`,
    vid: `champion_videos/c-o-animated-katarina.mp4`,
    pickAudio: `audio/champion_audio/katarina/pick/0.ogg`,
    banAudio: `audio/champion_audio/katarina/ban/0.ogg`,
  },
  kayle: {
    suspended: false,
    name: "Kayle",
    loadingImg: `img/champion/loading/Kayle_0.jpg`,
    splashImg: `img/champion/splash/Kayle_0.jpg`,
    tileImg: `img/champion/tiles/Kayle_0.jpg`,
    vid: `champion_videos/c-o-animated-kayle.mp4`,
    pickAudio: `audio/champion_audio/kayle/pick/0.ogg`,
    banAudio: `audio/champion_audio/kayle/ban/0.ogg`,
  },
  kayn: {
    suspended: false,
    name: "Kayn",
    loadingImg: `img/champion/loading/Kayn_0.jpg`,
    splashImg: `img/champion/splash/Kayn_0.jpg`,
    tileImg: `img/champion/tiles/Kayn_0.jpg`,
    vid: `champion_videos/c-o-animated-kayn.mp4`,
    pickAudio: `audio/champion_audio/kayn/pick/0.ogg`,
    banAudio: `audio/champion_audio/kayn/ban/0.ogg`,
  },
  kennen: {
    suspended: false,
    name: "Kennen",
    loadingImg: `img/champion/loading/Kennen_0.jpg`,
    splashImg: `img/champion/splash/Kennen_0.jpg`,
    tileImg: `img/champion/tiles/Kennen_0.jpg`,
    vid: `champion_videos/c-o-animated-kennen.mp4`,
    pickAudio: `audio/champion_audio/kennen/pick/0.ogg`,
    banAudio: `audio/champion_audio/kennen/ban/0.ogg`,
  },
  khazix: {
    suspended: false,
    name: "Kha'Zix",
    loadingImg: `img/champion/loading/Khazix_0.jpg`,
    splashImg: `img/champion/splash/Khazix_0.jpg`,
    tileImg: `img/champion/tiles/Khazix_0.jpg`,
    vid: `champion_videos/c-o-animated-khazix.mp4`,
    pickAudio: `audio/champion_audio/khazix/pick/0.ogg`,
    banAudio: `audio/champion_audio/khazix/ban/0.ogg`,
  },
  kindred: {
    suspended: false,
    name: "Kindred",
    loadingImg: `img/champion/loading/Kindred_0.jpg`,
    splashImg: `img/champion/splash/Kindred_0.jpg`,
    tileImg: `img/champion/tiles/Kindred_0.jpg`,
    vid: `champion_videos/c-o-animated-kindred.mp4`,
    pickAudio: `audio/champion_audio/kindred/pick/0.ogg`,
    banAudio: `audio/champion_audio/kindred/ban/0.ogg`,
  },
  kled: {
    suspended: false,
    name: "Kled",
    loadingImg: `img/champion/loading/Kled_0.jpg`,
    splashImg: `img/champion/splash/Kled_0.jpg`,
    tileImg: `img/champion/tiles/Kled_0.jpg`,
    vid: `champion_videos/c-o-animated-kled.mp4`,
    pickAudio: `audio/champion_audio/kled/pick/0.ogg`,
    banAudio: `audio/champion_audio/kled/ban/0.ogg`,
  },
  kogmaw: {
    suspended: false,
    name: "Kogmaw",
    loadingImg: `img/champion/loading/KogMaw_0.jpg`,
    splashImg: `img/champion/splash/KogMaw_0.jpg`,
    tileImg: `img/champion/tiles/KogMaw_0.jpg`,
    vid: `champion_videos/c-o-animated-kogmaw.mp4`,
    pickAudio: `audio/champion_audio/kogmaw/pick/0.ogg`,
    banAudio: `audio/champion_audio/kogmaw/ban/0.ogg`,
  },
  leblanc: {
    suspended: false,
    name: "Leblanc",
    loadingImg: `img/champion/loading/Leblanc_0.jpg`,
    splashImg: `img/champion/splash/Leblanc_0.jpg`,
    tileImg: `img/champion/tiles/Leblanc_0.jpg`,
    vid: `champion_videos/c-o-animated-leblanc.mp4`,
    pickAudio: `audio/champion_audio/leblanc/pick/0.ogg`,
    banAudio: `audio/champion_audio/leblanc/ban/0.ogg`,
  },
  leesin: {
    suspended: false,
    name: "Lee Sin",
    loadingImg: `img/champion/loading/LeeSin_0.jpg`,
    splashImg: `img/champion/splash/LeeSin_0.jpg`,
    tileImg: `img/champion/tiles/LeeSin_0.jpg`,
    vid: `champion_videos/c-o-animated-leesin.mp4`,
    pickAudio: `audio/champion_audio/leesin/pick/0.ogg`,
    banAudio: `audio/champion_audio/leesin/ban/0.ogg`,
  },
  leona: {
    suspended: false,
    name: "Leona",
    loadingImg: `img/champion/loading/Leona_0.jpg`,
    splashImg: `img/champion/splash/Leona_0.jpg`,
    tileImg: `img/champion/tiles/Leona_0.jpg`,
    vid: `champion_videos/c-o-animated-leona.mp4`,
    pickAudio: `audio/champion_audio/leona/pick/0.ogg`,
    banAudio: `audio/champion_audio/leona/ban/0.ogg`,
  },
  lillia: {
    suspended: false,
    name: "Lillia",
    loadingImg: `img/champion/loading/Lillia_0.jpg`,
    splashImg: `img/champion/splash/Lillia_0.jpg`,
    tileImg: `img/champion/tiles/Lillia_0.jpg`,
    vid: `champion_videos/c-o-animated-lillia.mp4`,
    pickAudio: `audio/champion_audio/lillia/pick/0.ogg`,
    banAudio: `audio/champion_audio/lillia/ban/0.ogg`,
  },
  lissandra: {
    suspended: false,
    name: "Lissandra",
    loadingImg: `img/champion/loading/Lissandra_0.jpg`,
    splashImg: `img/champion/splash/Lissandra_0.jpg`,
    tileImg: `img/champion/tiles/Lissandra_0.jpg`,
    vid: `champion_videos/c-o-animated-lissandra.mp4`,
    pickAudio: `audio/champion_audio/lissandra/pick/0.ogg`,
    banAudio: `audio/champion_audio/lissandra/ban/0.ogg`,
  },
  lucian: {
    suspended: false,
    name: "Lucian",
    loadingImg: `img/champion/loading/Lucian_0.jpg`,
    splashImg: `img/champion/splash/Lucian_0.jpg`,
    tileImg: `img/champion/tiles/Lucian_0.jpg`,
    vid: `champion_videos/c-o-animated-lucian.mp4`,
    pickAudio: `audio/champion_audio/lucian/pick/0.ogg`,
    banAudio: `audio/champion_audio/lucian/ban/0.ogg`,
  },
  lulu: {
    suspended: false,
    name: "Lulu",
    loadingImg: `img/champion/loading/Lulu_0.jpg`,
    splashImg: `img/champion/splash/Lulu_0.jpg`,
    tileImg: `img/champion/tiles/Lulu_0.jpg`,
    vid: `champion_videos/c-o-animated-lulu.mp4`,
    pickAudio: `audio/champion_audio/lulu/pick/0.ogg`,
    banAudio: `audio/champion_audio/lulu/ban/0.ogg`,
  },
  lux: {
    suspended: false,
    name: "Lux",
    loadingImg: `img/champion/loading/Lux_0.jpg`,
    splashImg: `img/champion/splash/Lux_0.jpg`,
    tileImg: `img/champion/tiles/Lux_0.jpg`,
    vid: `champion_videos/c-o-animated-lux.mp4`,
    pickAudio: `audio/champion_audio/lux/pick/0.ogg`,
    banAudio: `audio/champion_audio/lux/ban/0.ogg`,
  },
  malphite: {
    suspended: false,
    name: "Malphite",
    loadingImg: `img/champion/loading/Malphite_0.jpg`,
    splashImg: `img/champion/splash/Malphite_0.jpg`,
    tileImg: `img/champion/tiles/Malphite_0.jpg`,
    vid: `champion_videos/c-o-animated-malphite.mp4`,
    pickAudio: `audio/champion_audio/malphite/pick/0.ogg`,
    banAudio: `audio/champion_audio/malphite/ban/0.ogg`,
  },
  malzahar: {
    suspended: false,
    name: "Malzahar",
    loadingImg: `img/champion/loading/Malzahar_0.jpg`,
    splashImg: `img/champion/splash/Malzahar_0.jpg`,
    tileImg: `img/champion/tiles/Malzahar_0.jpg`,
    vid: `champion_videos/c-o-animated-malzahar.mp4`,
    pickAudio: `audio/champion_audio/malzahar/pick/0.ogg`,
    banAudio: `audio/champion_audio/malzahar/ban/0.ogg`,
  },
  maokai: {
    suspended: false,
    name: "Maokai",
    loadingImg: `img/champion/loading/Maokai_0.jpg`,
    splashImg: `img/champion/splash/Maokai_0.jpg`,
    tileImg: `img/champion/tiles/Maokai_0.jpg`,
    vid: `champion_videos/c-o-animated-maokai.mp4`,
    pickAudio: `audio/champion_audio/maokai/pick/0.ogg`,
    banAudio: `audio/champion_audio/maokai/ban/0.ogg`,
  },
  masteryi: {
    suspended: false,
    name: "Master Yi",
    loadingImg: `img/champion/loading/MasterYi_0.jpg`,
    splashImg: `img/champion/splash/MasterYi_0.jpg`,
    tileImg: `img/champion/tiles/MasterYi_0.jpg`,
    vid: `champion_videos/c-o-animated-masteryi.mp4`,
    pickAudio: `audio/champion_audio/masteryi/pick/0.ogg`,
    banAudio: `audio/champion_audio/masteryi/ban/0.ogg`,
  },
  missfortune: {
    suspended: false,
    name: "Miss Fortune",
    loadingImg: `img/champion/loading/MissFortune_0.jpg`,
    splashImg: `img/champion/splash/MissFortune_0.jpg`,
    tileImg: `img/champion/tiles/MissFortune_0.jpg`,
    vid: `champion_videos/c-o-animated-missfortune.mp4`,
    pickAudio: `audio/champion_audio/missfortune/pick/0.ogg`,
    banAudio: `audio/champion_audio/missfortune/ban/0.ogg`,
  },
  mordekaiser: {
    suspended: false,
    name: "Mordekaiser",
    loadingImg: `img/champion/loading/Mordekaiser_0.jpg`,
    splashImg: `img/champion/splash/Mordekaiser_0.jpg`,
    tileImg: `img/champion/tiles/Mordekaiser_0.jpg`,
    vid: `champion_videos/c-o-animated-mordekaiser.mp4`,
    pickAudio: `audio/champion_audio/mordekaiser/pick/0.ogg`,
    banAudio: `audio/champion_audio/mordekaiser/ban/0.ogg`,
  },
  morgana: {
    suspended: false,
    name: "Morgana",
    loadingImg: `img/champion/loading/Morgana_0.jpg`,
    splashImg: `img/champion/splash/Morgana_0.jpg`,
    tileImg: `img/champion/tiles/Morgana_0.jpg`,
    vid: `champion_videos/c-o-animated-morgana.mp4`,
    pickAudio: `audio/champion_audio/morgana/pick/0.ogg`,
    banAudio: `audio/champion_audio/morgana/ban/0.ogg`,
  },
  nami: {
    suspended: false,
    name: "Nami",
    loadingImg: `img/champion/loading/Nami_0.jpg`,
    splashImg: `img/champion/splash/Nami_0.jpg`,
    tileImg: `img/champion/tiles/Nami_0.jpg`,
    vid: `champion_videos/c-o-animated-nami.mp4`,
    pickAudio: `audio/champion_audio/nami/pick/0.ogg`,
    banAudio: `audio/champion_audio/nami/ban/0.ogg`,
  },
  nasus: {
    suspended: false,
    name: "Nasus",
    loadingImg: `img/champion/loading/Nasus_0.jpg`,
    splashImg: `img/champion/splash/Nasus_0.jpg`,
    tileImg: `img/champion/tiles/Nasus_0.jpg`,
    vid: `champion_videos/c-o-animated-nasus.mp4`,
    pickAudio: `audio/champion_audio/nasus/pick/0.ogg`,
    banAudio: `audio/champion_audio/nasus/ban/0.ogg`,
  },
  nautilus: {
    suspended: false,
    name: "Nautilus",
    loadingImg: `img/champion/loading/Nautilus_0.jpg`,
    splashImg: `img/champion/splash/Nautilus_0.jpg`,
    tileImg: `img/champion/tiles/Nautilus_0.jpg`,
    vid: `champion_videos/c-o-animated-nautilus.mp4`,
    pickAudio: `audio/champion_audio/nautilus/pick/0.ogg`,
    banAudio: `audio/champion_audio/nautilus/ban/0.ogg`,
  },
  neeko: {
    suspended: false,
    name: "Neeko",
    loadingImg: `img/champion/loading/Neeko_0.jpg`,
    splashImg: `img/champion/splash/Neeko_0.jpg`,
    tileImg: `img/champion/tiles/Neeko_0.jpg`,
    vid: `champion_videos/c-o-animated-neeko.mp4`,
    pickAudio: `audio/champion_audio/neeko/pick/0.ogg`,
    banAudio: `audio/champion_audio/neeko/ban/0.ogg`,
  },
  nidalee: {
    suspended: false,
    name: "Nidalee",
    loadingImg: `img/champion/loading/Nidalee_0.jpg`,
    splashImg: `img/champion/splash/Nidalee_0.jpg`,
    tileImg: `img/champion/tiles/Nidalee_0.jpg`,
    vid: `champion_videos/c-o-animated-nidalee.mp4`,
    pickAudio: `audio/champion_audio/nidalee/pick/0.ogg`,
    banAudio: `audio/champion_audio/nidalee/ban/0.ogg`,
  },
  nocturne: {
    suspended: false,
    name: "Nocturne",
    loadingImg: `img/champion/loading/Nocturne_0.jpg`,
    splashImg: `img/champion/splash/Nocturne_0.jpg`,
    tileImg: `img/champion/tiles/Nocturne_0.jpg`,
    vid: `champion_videos/c-o-animated-nocturne.mp4`,
    pickAudio: `audio/champion_audio/nocturne/pick/0.ogg`,
    banAudio: `audio/champion_audio/nocturne/ban/0.ogg`,
  },
  nunu: {
    suspended: false,
    name: "Nunu",
    loadingImg: `img/champion/loading/Nunu_0.jpg`,
    splashImg: `img/champion/splash/Nunu_0.jpg`,
    tileImg: `img/champion/tiles/Nunu_0.jpg`,
    vid: `champion_videos/c-o-animated-nunu.mp4`,
    pickAudio: `audio/champion_audio/nunu/pick/0.ogg`,
    banAudio: `audio/champion_audio/nunu/ban/0.ogg`,
  },
  olaf: {
    suspended: false,
    name: "Olaf",
    loadingImg: `img/champion/loading/Olaf_0.jpg`,
    splashImg: `img/champion/splash/Olaf_0.jpg`,
    tileImg: `img/champion/tiles/Olaf_0.jpg`,
    vid: `champion_videos/c-o-animated-olaf.mp4`,
    pickAudio: `audio/champion_audio/olaf/pick/0.ogg`,
    banAudio: `audio/champion_audio/olaf/ban/0.ogg`,
  },
  orianna: {
    suspended: false,
    name: "Orianna",
    loadingImg: `img/champion/loading/Orianna_0.jpg`,
    splashImg: `img/champion/splash/Orianna_0.jpg`,
    tileImg: `img/champion/tiles/Orianna_0.jpg`,
    vid: `champion_videos/c-o-animated-orianna.mp4`,
    pickAudio: `audio/champion_audio/orianna/pick/0.ogg`,
    banAudio: `audio/champion_audio/orianna/ban/0.ogg`,
  },
  ornn: {
    suspended: false,
    name: "Ornn",
    loadingImg: `img/champion/loading/Ornn_0.jpg`,
    splashImg: `img/champion/splash/Ornn_0.jpg`,
    tileImg: `img/champion/tiles/Ornn_0.jpg`,
    vid: `champion_videos/c-o-animated-ornn.mp4`,
    pickAudio: `audio/champion_audio/ornn/pick/0.ogg`,
    banAudio: `audio/champion_audio/ornn/ban/0.ogg`,
  },
  pantheon: {
    suspended: false,
    name: "Pantheon",
    loadingImg: `img/champion/loading/Pantheon_0.jpg`,
    splashImg: `img/champion/splash/Pantheon_0.jpg`,
    tileImg: `img/champion/tiles/Pantheon_0.jpg`,
    vid: `champion_videos/c-o-animated-pantheon.mp4`,
    pickAudio: `audio/champion_audio/pantheon/pick/0.ogg`,
    banAudio: `audio/champion_audio/pantheon/ban/0.ogg`,
  },
  poppy: {
    suspended: false,
    name: "Poppy",
    loadingImg: `img/champion/loading/Poppy_0.jpg`,
    splashImg: `img/champion/splash/Poppy_0.jpg`,
    tileImg: `img/champion/tiles/Poppy_0.jpg`,
    vid: `champion_videos/c-o-animated-poppy.mp4`,
    pickAudio: `audio/champion_audio/poppy/pick/0.ogg`,
    banAudio: `audio/champion_audio/poppy/ban/0.ogg`,
  },
  pyke: {
    suspended: false,
    name: "Pyke",
    loadingImg: `img/champion/loading/Pyke_0.jpg`,
    splashImg: `img/champion/splash/Pyke_0.jpg`,
    tileImg: `img/champion/tiles/Pyke_0.jpg`,
    vid: `champion_videos/c-o-animated-pyke.mp4`,
    pickAudio: `audio/champion_audio/pyke/pick/0.ogg`,
    banAudio: `audio/champion_audio/pyke/ban/0.ogg`,
  },
  qiyana: {
    suspended: false,
    name: "Qiyana",
    loadingImg: `img/champion/loading/Qiyana_0.jpg`,
    splashImg: `img/champion/splash/Qiyana_0.jpg`,
    tileImg: `img/champion/tiles/Qiyana_0.jpg`,
    vid: `champion_videos/c-o-animated-qiyana.mp4`,
    pickAudio: `audio/champion_audio/qiyana/pick/0.ogg`,
    banAudio: `audio/champion_audio/qiyana/ban/0.ogg`,
  },
  quinn: {
    suspended: false,
    name: "Quinn",
    loadingImg: `img/champion/loading/Quinn_0.jpg`,
    splashImg: `img/champion/splash/Quinn_0.jpg`,
    tileImg: `img/champion/tiles/Quinn_0.jpg`,
    vid: `champion_videos/c-o-animated-quinn.mp4`,
    pickAudio: `audio/champion_audio/quinn/pick/0.ogg`,
    banAudio: `audio/champion_audio/quinn/ban/0.ogg`,
  },
  rakan: {
    suspended: false,
    name: "Rakan",
    loadingImg: `img/champion/loading/Rakan_0.jpg`,
    splashImg: `img/champion/splash/Rakan_0.jpg`,
    tileImg: `img/champion/tiles/Rakan_0.jpg`,
    vid: `champion_videos/c-o-animated-rakan.mp4`,
    pickAudio: `audio/champion_audio/rakan/pick/0.ogg`,
    banAudio: `audio/champion_audio/rakan/ban/0.ogg`,
  },
  rammus: {
    suspended: false,
    name: "Rammus",
    loadingImg: `img/champion/loading/Rammus_0.jpg`,
    splashImg: `img/champion/splash/Rammus_0.jpg`,
    tileImg: `img/champion/tiles/Rammus_0.jpg`,
    vid: `champion_videos/c-o-animated-rammus.mp4`,
    pickAudio: `audio/champion_audio/rammus/pick/0.ogg`,
    banAudio: `audio/champion_audio/rammus/ban/0.ogg`,
  },
  reksai: {
    suspended: false,
    name: "Rek'Sai",
    loadingImg: `img/champion/loading/RekSai_0.jpg`,
    splashImg: `img/champion/splash/RekSai_0.jpg`,
    tileImg: `img/champion/tiles/RekSai_0.jpg`,
    vid: `champion_videos/c-o-animated-reksai.mp4`,
    pickAudio: `audio/champion_audio/reksai/pick/0.ogg`,
    banAudio: `audio/champion_audio/reksai/ban/0.ogg`,
  },
  renekton: {
    suspended: false,
    name: "Renekton",
    loadingImg: `img/champion/loading/Renekton_0.jpg`,
    splashImg: `img/champion/splash/Renekton_0.jpg`,
    tileImg: `img/champion/tiles/Renekton_0.jpg`,
    vid: `champion_videos/c-o-animated-renekton.mp4`,
    pickAudio: `audio/champion_audio/renekton/pick/0.ogg`,
    banAudio: `audio/champion_audio/renekton/ban/0.ogg`,
  },
  rengar: {
    suspended: false,
    name: "Rengar",
    loadingImg: `img/champion/loading/Rengar_0.jpg`,
    splashImg: `img/champion/splash/Rengar_0.jpg`,
    tileImg: `img/champion/tiles/Rengar_0.jpg`,
    vid: `champion_videos/c-o-animated-rengar.mp4`,
    pickAudio: `audio/champion_audio/rengar/pick/0.ogg`,
    banAudio: `audio/champion_audio/rengar/ban/0.ogg`,
  },
  riven: {
    suspended: false,
    name: "Riven",
    loadingImg: `img/champion/loading/Riven_0.jpg`,
    splashImg: `img/champion/splash/Riven_0.jpg`,
    tileImg: `img/champion/tiles/Riven_0.jpg`,
    vid: `champion_videos/c-o-animated-riven.mp4`,
    pickAudio: `audio/champion_audio/riven/pick/0.ogg`,
    banAudio: `audio/champion_audio/riven/ban/0.ogg`,
  },
  rumble: {
    suspended: false,
    name: "Rumble",
    loadingImg: `img/champion/loading/Rumble_0.jpg`,
    splashImg: `img/champion/splash/Rumble_0.jpg`,
    tileImg: `img/champion/tiles/Rumble_0.jpg`,
    vid: `champion_videos/c-o-animated-rumble.mp4`,
    pickAudio: `audio/champion_audio/rumble/pick/0.ogg`,
    banAudio: `audio/champion_audio/rumble/ban/0.ogg`,
  },
  ryze: {
    suspended: false,
    name: "Ryze",
    loadingImg: `img/champion/loading/Ryze_0.jpg`,
    splashImg: `img/champion/splash/Ryze_0.jpg`,
    tileImg: `img/champion/tiles/Ryze_0.jpg`,
    vid: `champion_videos/c-o-animated-ryze.mp4`,
    pickAudio: `audio/champion_audio/ryze/pick/0.ogg`,
    banAudio: `audio/champion_audio/ryze/ban/0.ogg`,
  },
  sejuani: {
    suspended: false,
    name: "Sejuani",
    loadingImg: `img/champion/loading/Sejuani_0.jpg`,
    splashImg: `img/champion/splash/Sejuani_0.jpg`,
    tileImg: `img/champion/tiles/Sejuani_0.jpg`,
    vid: `champion_videos/c-o-animated-sejuani.mp4`,
    pickAudio: `audio/champion_audio/sejuani/pick/0.ogg`,
    banAudio: `audio/champion_audio/sejuani/ban/0.ogg`,
  },
  senna: {
    suspended: false,
    name: "Senna",
    loadingImg: `img/champion/loading/Senna_0.jpg`,
    splashImg: `img/champion/splash/Senna_0.jpg`,
    tileImg: `img/champion/tiles/Senna_0.jpg`,
    vid: `champion_videos/c-o-animated-senna.mp4`,
    pickAudio: `audio/champion_audio/senna/pick/0.ogg`,
    banAudio: `audio/champion_audio/senna/ban/0.ogg`,
  },
  sett: {
    suspended: false,
    name: "Sett",
    loadingImg: `img/champion/loading/Sett_0.jpg`,
    splashImg: `img/champion/splash/Sett_0.jpg`,
    tileImg: `img/champion/tiles/Sett_0.jpg`,
    vid: `champion_videos/c-o-animated-sett.mp4`,
    pickAudio: `audio/champion_audio/sett/pick/0.mp3`,
    banAudio: `audio/champion_audio/sett/ban/0.mp3`,
  },
  shaco: {
    suspended: false,
    name: "Shaco",
    loadingImg: `img/champion/loading/Shaco_0.jpg`,
    splashImg: `img/champion/splash/Shaco_0.jpg`,
    tileImg: `img/champion/tiles/Shaco_0.jpg`,
    vid: `champion_videos/c-o-animated-shaco.mp4`,
    pickAudio: `audio/champion_audio/shaco/pick/0.ogg`,
    banAudio: `audio/champion_audio/shaco/ban/0.ogg`,
  },
  shen: {
    suspended: false,
    name: "Shen",
    loadingImg: `img/champion/loading/Shen_0.jpg`,
    splashImg: `img/champion/splash/Shen_0.jpg`,
    tileImg: `img/champion/tiles/Shen_0.jpg`,
    vid: `champion_videos/c-o-animated-shen.mp4`,
    pickAudio: `audio/champion_audio/shen/pick/0.ogg`,
    banAudio: `audio/champion_audio/shen/ban/0.ogg`,
  },
  shyvana: {
    suspended: false,
    name: "Shyvana",
    loadingImg: `img/champion/loading/Shyvana_0.jpg`,
    splashImg: `img/champion/splash/Shyvana_0.jpg`,
    tileImg: `img/champion/tiles/Shyvana_0.jpg`,
    vid: `champion_videos/c-o-animated-shyvana.mp4`,
    pickAudio: `audio/champion_audio/shyvana/pick/0.ogg`,
    banAudio: `audio/champion_audio/shyvana/ban/0.ogg`,
  },
  singed: {
    suspended: false,
    name: "Singed",
    loadingImg: `img/champion/loading/Singed_0.jpg`,
    splashImg: `img/champion/splash/Singed_0.jpg`,
    tileImg: `img/champion/tiles/Singed_0.jpg`,
    vid: `champion_videos/c-o-animated-singed.mp4`,
    pickAudio: `audio/champion_audio/singed/pick/0.ogg`,
    banAudio: `audio/champion_audio/singed/ban/0.ogg`,
  },
  sion: {
    suspended: false,
    name: "Sion",
    loadingImg: `img/champion/loading/Sion_0.jpg`,
    splashImg: `img/champion/splash/Sion_0.jpg`,
    tileImg: `img/champion/tiles/Sion_0.jpg`,
    vid: `champion_videos/c-o-animated-sion.mp4`,
    pickAudio: `audio/champion_audio/sion/pick/0.ogg`,
    banAudio: `audio/champion_audio/sion/ban/0.ogg`,
  },
  sivir: {
    suspended: false,
    name: "Sivir",
    loadingImg: `img/champion/loading/Sivir_0.jpg`,
    splashImg: `img/champion/splash/Sivir_0.jpg`,
    tileImg: `img/champion/tiles/Sivir_0.jpg`,
    vid: `champion_videos/c-o-animated-sivir.mp4`,
    pickAudio: `audio/champion_audio/sivir/pick/0.ogg`,
    banAudio: `audio/champion_audio/sivir/ban/0.ogg`,
  },
  skarner: {
    suspended: false,
    name: "Skarner",
    loadingImg: `img/champion/loading/Skarner_0.jpg`,
    splashImg: `img/champion/splash/Skarner_0.jpg`,
    tileImg: `img/champion/tiles/Skarner_0.jpg`,
    vid: `champion_videos/c-o-animated-skarner.mp4`,
    pickAudio: `audio/champion_audio/skarner/pick/0.ogg`,
    banAudio: `audio/champion_audio/skarner/ban/0.ogg`,
  },
  sona: {
    suspended: false,
    name: "Sona",
    loadingImg: `img/champion/loading/Sona_0.jpg`,
    splashImg: `img/champion/splash/Sona_0.jpg`,
    tileImg: `img/champion/tiles/Sona_0.jpg`,
    vid: `champion_videos/c-o-animated-sona.mp4`,
    pickAudio: `audio/champion_audio/sona/pick/0.ogg`,
    banAudio: `audio/champion_audio/sona/ban/0.ogg`,
  },
  soraka: {
    suspended: false,
    name: "Soraka",
    loadingImg: `img/champion/loading/Soraka_0.jpg`,
    splashImg: `img/champion/splash/Soraka_0.jpg`,
    tileImg: `img/champion/tiles/Soraka_0.jpg`,
    vid: `champion_videos/c-o-animated-soraka.mp4`,
    pickAudio: `audio/champion_audio/soraka/pick/0.ogg`,
    banAudio: `audio/champion_audio/soraka/ban/0.ogg`,
  },
  swain: {
    suspended: false,
    name: "Swain",
    loadingImg: `img/champion/loading/Swain_0.jpg`,
    splashImg: `img/champion/splash/Swain_0.jpg`,
    tileImg: `img/champion/tiles/Swain_0.jpg`,
    vid: `champion_videos/c-o-animated-swain.mp4`,
    pickAudio: `audio/champion_audio/swain/pick/0.ogg`,
    banAudio: `audio/champion_audio/swain/ban/0.ogg`,
  },
  sylas: {
    suspended: false,
    name: "Sylas",
    loadingImg: `img/champion/loading/Sylas_0.jpg`,
    splashImg: `img/champion/splash/Sylas_0.jpg`,
    tileImg: `img/champion/tiles/Sylas_0.jpg`,
    vid: `champion_videos/c-o-animated-sylas.mp4`,
    pickAudio: `audio/champion_audio/sylas/pick/0.ogg`,
    banAudio: `audio/champion_audio/sylas/ban/0.ogg`,
  },
  syndra: {
    suspended: false,
    name: "Syndra",
    loadingImg: `img/champion/loading/Syndra_0.jpg`,
    splashImg: `img/champion/splash/Syndra_0.jpg`,
    tileImg: `img/champion/tiles/Syndra_0.jpg`,
    vid: `champion_videos/c-o-animated-syndra.mp4`,
    pickAudio: `audio/champion_audio/syndra/pick/0.ogg`,
    banAudio: `audio/champion_audio/syndra/ban/0.ogg`,
  },
  tahmkench: {
    suspended: false,
    name: "Tahm Kench",
    loadingImg: `img/champion/loading/TahmKench_0.jpg`,
    splashImg: `img/champion/splash/TahmKench_0.jpg`,
    tileImg: `img/champion/tiles/TahmKench_0.jpg`,
    vid: `champion_videos/c-o-animated-tahmkench.mp4`,
    pickAudio: `audio/champion_audio/tahmkench/pick/0.ogg`,
    banAudio: `audio/champion_audio/tahmkench/ban/0.ogg`,
  },
  taliyah: {
    suspended: false,
    name: "Taliyah",
    loadingImg: `img/champion/loading/Taliyah_0.jpg`,
    splashImg: `img/champion/splash/Taliyah_0.jpg`,
    tileImg: `img/champion/tiles/Taliyah_0.jpg`,
    vid: `champion_videos/c-o-animated-taliyah.mp4`,
    pickAudio: `audio/champion_audio/taliyah/pick/0.ogg`,
    banAudio: `audio/champion_audio/taliyah/ban/0.ogg`,
  },
  talon: {
    suspended: false,
    name: "Talon",
    loadingImg: `img/champion/loading/Talon_0.jpg`,
    splashImg: `img/champion/splash/Talon_0.jpg`,
    tileImg: `img/champion/tiles/Talon_0.jpg`,
    vid: `champion_videos/c-o-animated-talon.mp4`,
    pickAudio: `audio/champion_audio/talon/pick/0.ogg`,
    banAudio: `audio/champion_audio/talon/ban/0.ogg`,
  },
  taric: {
    suspended: false,
    name: "Taric",
    loadingImg: `img/champion/loading/Taric_0.jpg`,
    splashImg: `img/champion/splash/Taric_0.jpg`,
    tileImg: `img/champion/tiles/Taric_0.jpg`,
    vid: `champion_videos/c-o-animated-taric.mp4`,
    pickAudio: `audio/champion_audio/taric/pick/0.ogg`,
    banAudio: `audio/champion_audio/taric/ban/0.ogg`,
  },
  teemo: {
    suspended: false,
    name: "Teemo",
    loadingImg: `img/champion/loading/Teemo_0.jpg`,
    splashImg: `img/champion/splash/Teemo_0.jpg`,
    tileImg: `img/champion/tiles/Teemo_0.jpg`,
    vid: `champion_videos/c-o-animated-teemo.mp4`,
    pickAudio: `audio/champion_audio/teemo/pick/0.ogg`,
    banAudio: `audio/champion_audio/teemo/ban/0.ogg`,
  },
  thresh: {
    suspended: false,
    name: "Thresh",
    loadingImg: `img/champion/loading/Thresh_0.jpg`,
    splashImg: `img/champion/splash/Thresh_0.jpg`,
    tileImg: `img/champion/tiles/Thresh_0.jpg`,
    vid: `champion_videos/c-o-animated-thresh.mp4`,
    pickAudio: `audio/champion_audio/thresh/pick/0.ogg`,
    banAudio: `audio/champion_audio/thresh/ban/0.ogg`,
  },
  tristana: {
    suspended: false,
    name: "Tristana",
    loadingImg: `img/champion/loading/Tristana_0.jpg`,
    splashImg: `img/champion/splash/Tristana_0.jpg`,
    tileImg: `img/champion/tiles/Tristana_0.jpg`,
    vid: `champion_videos/c-o-animated-tristana.mp4`,
    pickAudio: `audio/champion_audio/tristana/pick/0.ogg`,
    banAudio: `audio/champion_audio/tristana/ban/0.ogg`,
  },
  trundle: {
    suspended: false,
    name: "Trundle",
    loadingImg: `img/champion/loading/Trundle_0.jpg`,
    splashImg: `img/champion/splash/Trundle_0.jpg`,
    tileImg: `img/champion/tiles/Trundle_0.jpg`,
    vid: `champion_videos/c-o-animated-trundle.mp4`,
    pickAudio: `audio/champion_audio/trundle/pick/0.ogg`,
    banAudio: `audio/champion_audio/trundle/ban/0.ogg`,
  },
  tryndamere: {
    suspended: false,
    name: "Tryndamere",
    loadingImg: `img/champion/loading/Tryndamere_0.jpg`,
    splashImg: `img/champion/splash/Tryndamere_0.jpg`,
    tileImg: `img/champion/tiles/Tryndamere_0.jpg`,
    vid: `champion_videos/c-o-animated-tryndamere.mp4`,
    pickAudio: `audio/champion_audio/tryndamere/pick/0.ogg`,
    banAudio: `audio/champion_audio/tryndamere/ban/0.ogg`,
  },
  twistedfate: {
    suspended: false,
    name: "Twisted Fate",
    loadingImg: `img/champion/loading/TwistedFate_0.jpg`,
    splashImg: `img/champion/splash/TwistedFate_0.jpg`,
    tileImg: `img/champion/tiles/TwistedFate_0.jpg`,
    vid: `champion_videos/c-o-animated-twistedfate.mp4`,
    pickAudio: `audio/champion_audio/twistedfate/pick/0.ogg`,
    banAudio: `audio/champion_audio/twistedfate/ban/0.ogg`,
  },
  twitch: {
    suspended: false,
    name: "Twitch",
    loadingImg: `img/champion/loading/Twitch_0.jpg`,
    splashImg: `img/champion/splash/Twitch_0.jpg`,
    tileImg: `img/champion/tiles/Twitch_0.jpg`,
    vid: `champion_videos/c-o-animated-twitch.mp4`,
    pickAudio: `audio/champion_audio/twitch/pick/0.ogg`,
    banAudio: `audio/champion_audio/twitch/ban/0.ogg`,
  },
  udyr: {
    suspended: false,
    name: "Udyr",
    loadingImg: `img/champion/loading/Udyr_0.jpg`,
    splashImg: `img/champion/splash/Udyr_0.jpg`,
    tileImg: `img/champion/tiles/Udyr_0.jpg`,
    vid: `champion_videos/c-o-animated-udyr.mp4`,
    pickAudio: `audio/champion_audio/udyr/pick/0.ogg`,
    banAudio: `audio/champion_audio/udyr/ban/0.ogg`,
  },
  urf: {
    suspended: false,
    name: "Urf",
    vid: `champion_videos/c-o-animated-urf.mp4`,
    pickAudio: `audio/champion_audio/urf/pick/0.ogg`,
    banAudio: `audio/champion_audio/urf/ban/0.ogg`,
  },
  urgot: {
    suspended: false,
    name: "Urgot",
    loadingImg: `img/champion/loading/Urgot_0.jpg`,
    splashImg: `img/champion/splash/Urgot_0.jpg`,
    tileImg: `img/champion/tiles/Urgot_0.jpg`,
    vid: `champion_videos/c-o-animated-urgot.mp4`,
    pickAudio: `audio/champion_audio/urgot/pick/0.ogg`,
    banAudio: `audio/champion_audio/urgot/ban/0.ogg`,
  },
  varus: {
    suspended: false,
    name: "Varus",
    loadingImg: `img/champion/loading/Varus_0.jpg`,
    splashImg: `img/champion/splash/Varus_0.jpg`,
    tileImg: `img/champion/tiles/Varus_0.jpg`,
    vid: `champion_videos/c-o-animated-varus.mp4`,
    pickAudio: `audio/champion_audio/varus/pick/0.ogg`,
    banAudio: `audio/champion_audio/varus/ban/0.ogg`,
  },
  vayne: {
    suspended: false,
    name: "Vayne",
    loadingImg: `img/champion/loading/Vayne_0.jpg`,
    splashImg: `img/champion/splash/Vayne_0.jpg`,
    tileImg: `img/champion/tiles/Vayne_0.jpg`,
    vid: `champion_videos/c-o-animated-vayne.mp4`,
    pickAudio: `audio/champion_audio/vayne/pick/0.ogg`,
    banAudio: `audio/champion_audio/vayne/ban/0.ogg`,
  },
  veigar: {
    suspended: false,
    name: "Veigar",
    loadingImg: `img/champion/loading/Veigar_0.jpg`,
    splashImg: `img/champion/splash/Veigar_0.jpg`,
    tileImg: `img/champion/tiles/Veigar_0.jpg`,
    vid: `champion_videos/c-o-animated-veigar.mp4`,
    pickAudio: `audio/champion_audio/veigar/pick/0.ogg`,
    banAudio: `audio/champion_audio/veigar/ban/0.ogg`,
  },
  velkoz: {
    suspended: false,
    name: "Vel'Koz",
    loadingImg: `img/champion/loading/Velkoz_0.jpg`,
    splashImg: `img/champion/splash/Velkoz_0.jpg`,
    tileImg: `img/champion/tiles/Velkoz_0.jpg`,
    vid: `champion_videos/c-o-animated-velkoz.mp4`,
    pickAudio: `audio/champion_audio/velkoz/pick/0.ogg`,
    banAudio: `audio/champion_audio/velkoz/ban/0.ogg`,
  },
  vi: {
    suspended: false,
    name: "Vi",
    loadingImg: `img/champion/loading/Vi_0.jpg`,
    splashImg: `img/champion/splash/Vi_0.jpg`,
    tileImg: `img/champion/tiles/Vi_0.jpg`,
    vid: `champion_videos/c-o-animated-vi.mp4`,
    pickAudio: `audio/champion_audio/vi/pick/0.ogg`,
    banAudio: `audio/champion_audio/vi/ban/0.ogg`,
  },
  viktor: {
    suspended: false,
    name: "Viktor",
    loadingImg: `img/champion/loading/Viktor_0.jpg`,
    splashImg: `img/champion/splash/Viktor_0.jpg`,
    tileImg: `img/champion/tiles/Viktor_0.jpg`,
    vid: `champion_videos/c-o-animated-viktor.mp4`,
    pickAudio: `audio/champion_audio/viktor/pick/0.ogg`,
    banAudio: `audio/champion_audio/viktor/ban/0.ogg`,
  },
  vladimir: {
    suspended: false,
    name: "Vladimir",
    loadingImg: `img/champion/loading/Vladimir_0.jpg`,
    splashImg: `img/champion/splash/Vladimir_0.jpg`,
    tileImg: `img/champion/tiles/Vladimir_0.jpg`,
    vid: `champion_videos/c-o-animated-vladimir.mp4`,
    pickAudio: `audio/champion_audio/vladimir/pick/0.ogg`,
    banAudio: `audio/champion_audio/vladimir/ban/0.ogg`,
  },
  volibear: {
    suspended: false,
    name: "Volibear",
    loadingImg: `img/champion/loading/Volibear_0.jpg`,
    splashImg: `img/champion/splash/Volibear_0.jpg`,
    tileImg: `img/champion/tiles/Volibear_0.jpg`,
    vid: `champion_videos/c-o-animated-volibear.mp4`,
    pickAudio: `audio/champion_audio/volibear/pick/0.ogg`,
    banAudio: `audio/champion_audio/volibear/ban/0.ogg`,
  },
  warwick: {
    suspended: false,
    name: "Warwick",
    loadingImg: `img/champion/loading/Warwick_0.jpg`,
    splashImg: `img/champion/splash/Warwick_0.jpg`,
    tileImg: `img/champion/tiles/Warwick_0.jpg`,
    vid: `champion_videos/c-o-animated-warwick.mp4`,
    pickAudio: `audio/champion_audio/warwick/pick/0.ogg`,
    banAudio: `audio/champion_audio/warwick/ban/0.ogg`,
  },
  wukong: {
    suspended: false,
    name: "Wukong",
    loadingImg: `img/champion/loading/MonkeyKing_0.jpg`,
    splashImg: `img/champion/splash/MonkeyKing_0.jpg`,
    tileImg: `img/champion/tiles/MonkeyKing_0.jpg`,
    vid: `champion_videos/c-o-animated-monkeyking.mp4`,
    pickAudio: `audio/champion_audio/monkeyking/pick/0.ogg`,
    banAudio: `audio/champion_audio/monkeyking/ban/0.ogg`,
  },
  xayah: {
    suspended: false,
    name: "Xayah",
    loadingImg: `img/champion/loading/Xayah_0.jpg`,
    splashImg: `img/champion/splash/Xayah_0.jpg`,
    tileImg: `img/champion/tiles/Xayah_0.jpg`,
    vid: `champion_videos/c-o-animated-xayah.mp4`,
    pickAudio: `audio/champion_audio/xayah/pick/0.ogg`,
    banAudio: `audio/champion_audio/xayah/ban/0.ogg`,
  },
  xerath: {
    suspended: false,
    name: "Xerath",
    loadingImg: `img/champion/loading/Xerath_0.jpg`,
    splashImg: `img/champion/splash/Xerath_0.jpg`,
    tileImg: `img/champion/tiles/Xerath_0.jpg`,
    vid: `champion_videos/c-o-animated-xerath.mp4`,
    pickAudio: `audio/champion_audio/xerath/pick/0.ogg`,
    banAudio: `audio/champion_audio/xerath/ban/0.ogg`,
  },
  xinzhao: {
    suspended: false,
    name: "Xin Zhao",
    loadingImg: `img/champion/loading/XinZhao_0.jpg`,
    splashImg: `img/champion/splash/XinZhao_0.jpg`,
    tileImg: `img/champion/tiles/XinZhao_0.jpg`,
    vid: `champion_videos/c-o-animated-xinzhao.mp4`,
    pickAudio: `audio/champion_audio/xinzhao/pick/0.ogg`,
    banAudio: `audio/champion_audio/xinzhao/ban/0.ogg`,
  },
  yasuo: {
    suspended: false,
    name: "Yasuo",
    loadingImg: `img/champion/loading/Yasuo_0.jpg`,
    splashImg: `img/champion/splash/Yasuo_0.jpg`,
    tileImg: `img/champion/tiles/Yasuo_0.jpg`,
    vid: `champion_videos/c-o-animated-yasuo.mp4`,
    pickAudio: `audio/champion_audio/yasuo/pick/0.ogg`,
    banAudio: `audio/champion_audio/yasuo/ban/0.ogg`,
  },
  yone: {
    suspended: false,
    name: "Yone",
    loadingImg: `img/champion/loading/Yone_0.jpg`,
    splashImg: `img/champion/splash/Yone_0.jpg`,
    tileImg: `img/champion/tiles/Yone_0.jpg`,
    vid: `champion_videos/c-o-animated-yone.mp4`,
    pickAudio: `audio/champion_audio/yone/pick/0.ogg`,
    banAudio: `audio/champion_audio/yone/ban/0.ogg`,
  },
  yorick: {
    suspended: false,
    name: "Yorick",
    loadingImg: `img/champion/loading/Yorick_0.jpg`,
    splashImg: `img/champion/splash/Yorick_0.jpg`,
    tileImg: `img/champion/tiles/Yorick_0.jpg`,
    vid: `champion_videos/c-o-animated-yorick.mp4`,
    pickAudio: `audio/champion_audio/yorick/pick/0.ogg`,
    banAudio: `audio/champion_audio/yorick/ban/0.ogg`,
  },
  yuumi: {
    suspended: false,
    name: "Yuumi",
    loadingImg: `img/champion/loading/Yuumi_0.jpg`,
    splashImg: `img/champion/splash/Yuumi_0.jpg`,
    tileImg: `img/champion/tiles/Yuumi_0.jpg`,
    vid: `champion_videos/c-o-animated-yuumi.mp4`,
    pickAudio: `audio/champion_audio/yuumi/pick/0.ogg`,
    banAudio: `audio/champion_audio/yuumi/ban/0.ogg`,
  },
  zac: {
    suspended: false,
    name: "Zac",
    loadingImg: `img/champion/loading/Zac_0.jpg`,
    splashImg: `img/champion/splash/Zac_0.jpg`,
    tileImg: `img/champion/tiles/Zac_0.jpg`,
    vid: `champion_videos/c-o-animated-zac.mp4`,
    pickAudio: `audio/champion_audio/zac/pick/0.ogg`,
    banAudio: `audio/champion_audio/zac/ban/0.ogg`,
  },
  zed: {
    suspended: false,
    name: "Zed",
    loadingImg: `img/champion/loading/Zed_0.jpg`,
    splashImg: `img/champion/splash/Zed_0.jpg`,
    tileImg: `img/champion/tiles/Zed_0.jpg`,
    vid: `champion_videos/c-o-animated-zed.mp4`,
    pickAudio: `audio/champion_audio/zed/pick/0.ogg`,
    banAudio: `audio/champion_audio/zed/ban/0.ogg`,
  },
  ziggs: {
    suspended: false,
    name: "Ziggs",
    loadingImg: `img/champion/loading/Ziggs_0.jpg`,
    splashImg: `img/champion/splash/Ziggs_0.jpg`,
    tileImg: `img/champion/tiles/Ziggs_0.jpg`,
    vid: `champion_videos/c-o-animated-ziggs.mp4`,
    pickAudio: `audio/champion_audio/ziggs/pick/0.ogg`,
    banAudio: `audio/champion_audio/ziggs/ban/0.ogg`,
  },
  zilean: {
    suspended: false,
    name: "Zilean",
    loadingImg: `img/champion/loading/Zilean_0.jpg`,
    splashImg: `img/champion/splash/Zilean_0.jpg`,
    tileImg: `img/champion/tiles/Zilean_0.jpg`,
    vid: `champion_videos/c-o-animated-zilean.mp4`,
    pickAudio: `audio/champion_audio/zilean/pick/0.ogg`,
    banAudio: `audio/champion_audio/zilean/ban/0.ogg`,
  },
  zoe: {
    suspended: false,
    name: "Zoe",
    loadingImg: `img/champion/loading/Zoe_0.jpg`,
    splashImg: `img/champion/splash/Zoe_0.jpg`,
    tileImg: `img/champion/tiles/Zoe_0.jpg`,
    vid: `champion_videos/c-o-animated-zoe-base.mp4`,
    pickAudio: `audio/champion_audio/zoe/pick/0.ogg`,
    banAudio: `audio/champion_audio/zoe/ban/0.ogg`,
  },
  zyra: {
    suspended: false,
    name: "Zyra",
    loadingImg: `img/champion/loading/Zyra_0.jpg`,
    splashImg: `img/champion/splash/Zyra_0.jpg`,
    tileImg: `img/champion/tiles/Zyra_0.jpg`,
    vid: `champion_videos/c-o-animated-zyra.mp4`,
    pickAudio: `audio/champion_audio/zyra/pick/0.ogg`,
    banAudio: `audio/champion_audio/zyra/ban/0.ogg`,
  },
};
